languageCode: en-US
title: Forrest Tutorial
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
baseUrl: "https://humanfactors.github.io/2022-Forrest-StaticBranding/" # Need to set this to correct subdomain
publishDir: "../docs/" # This is only for purpose of the tutorial
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Chris Turner
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Describe your website
  social:
    Email: email@example.com
    Github: username
    LinkedIn: username
    Medium: username
    RSS: /blog/index.xml
    Stackoverflow: username
    Telegram: username
    Twitter: username
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300
